---
- name: install kafka/config/server.properties
  become: yes
  become_user: root
  with_items:
    - f: server.properties
      d: '{{kafka_install_parent_dir}}'
      m: '0644'
    - f: kafka-broker.sh
      d: /etc/profile.d
      m: '0644'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
- include: '{{kafka_broker_init_system}}.yml'
